
export const ErrorCodes = {
  INVALID_PARAMS: 'INVALID_PARAMS',
  SYMBOL_NOT_AVAILABLE: 'SYMBOL_NOT_AVAILABLE',
  QUANTITY_TOO_SMALL: 'QUANTITY_TOO_SMALL',
  QUANTITY_TOO_LARGE: 'QUANTITY_TOO_LARGE',
  INSUFFICIENT_POSITION: 'INSUFFICIENT_POSITION',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_ORDER_RESPONSE: 'INVALID_ORDER_RESPONSE',
  INVALID_TRADE_TYPE: 'INVALID_TRADE_TYPE',
  PLACE_ORDER_ERROR: 'PLACE_ORDER_ERROR',
  PLACE_STRATEGY_ORDER_ERROR: 'PLACE_STRATEGY_ORDER_ERROR',
  CANCEL_ORDER_ERROR: 'CANCEL_ORDER_ERROR',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  SYMBOL_NOT_FOUND: 'SYMBOL_NOT_FOUND',
  PRICE_NOT_FOUND: 'PRICE_NOT_FOUND',
  TICKER_NOT_FOUND: 'TICKER_NOT_FOUND',
  ORDERBOOK_NOT_FOUND: 'ORDERBOOK_NOT_FOUND',
  MARK_PRICE_NOT_FOUND: 'MARK_PRICE_NOT_FOUND',
  BATCH_PLACE_ORDER_ERROR: 'BATCH_PLACE_ORDER_ERROR'
}
